### ISSUE TITLE
Ember Observer is an open source EmberJS Application

### ISSUE THREAD

**Issue by johno** [iheanyi/iheanyi.github.io#1]
Repo: https://github.com/emberobserver/client
App: http://emberobserver.com

Thought it might be a great addition to your [post](http://iheanyi.com/blog/a-list-of-open-source-emberjs-projects/).

**Comment by iheanyi** [comment]
Thanks @johnotander, I'll add it to the blog post! :)

**Comment by iheanyi** [comment]
Added!

**Comment by johno** [comment]
:smile_cat:  :+1:
