### ISSUE TITLE
Vine 

### ISSUE THREAD

**Issue by Robdel12** [iheanyi/iheanyi.github.io#2]
[Vine](http://vine.co) uses ember for their front end. 

![screen shot 2015-05-13 at 9 31 21 am](https://cloud.githubusercontent.com/assets/2072894/7612852/f0cbe92c-f952-11e4-99b7-671a8f9ba25c.png)

**Comment by iheanyi** [comment]
D'awww, while I know Vine uses EmberJS on the front-end, they don't have an open-source front-end client. :(

**Comment by Robdel12** [comment]
Ahhhhhh! I missed that. Still waking up :P
