### ISSUE TITLE
Unknown command: 'syncdb'

### ISSUE THREAD

**Issue by stevekinney** [iheanyi/iheanyi.github.io#5]
I'm working through the tutorial and making some little changes and adjustments [on a branch](https://github.com/stevekinney/iheanyi.github.io/tree/django-react-minor-revisions).

I should preface this my mentioning that I know almost nothing about Python and Django (and I thought that might actually be helpful). The first problem I ran into was on [Line 41](https://github.com/iheanyi/iheanyi.github.io/blame/develop/source/blog/user-registration-authentication-with-django-django-rest-framework-react-and-redux.html.markdown#L41).

```
python manage.py syncdb
```

I'm getting the following error:

```
Unknown command: 'syncdb'
Type 'manage.py help' for usage.
```

When I try `python manage.py help`, I get the following:

```

Type 'manage.py help <subcommand>' for help on a specific subcommand.

Available subcommands:

[auth]
    changepassword
    createsuperuser

[django]
    check
    compilemessages
    createcachetable
    dbshell
    diffsettings
    dumpdata
    flush
    inspectdb
    loaddata
    makemessages
    makemigrations
    migrate
    sendtestemail
    shell
    showmigrations
    sqlflush
    sqlmigrate
    sqlsequencereset
    squashmigrations
    startapp
    startproject
    test
    testserver

[sessions]
    clearsessions

[staticfiles]
    collectstatic
    findstatic
    runserver
```

Is there some other configuration that I need?

**Comment by iheanyi** [comment]
Eek, change that to `python manage.py migrate`. My bad on this, I think `syncdb` got deprecated ;_;

**Comment by iheanyi** [comment]
@stevekinney Did this solve your issues?
