### ISSUE TITLE
Commented-out code

### ISSUE THREAD

**Issue by GRardB** [iheanyi/iheanyi.github.io#6]
[An offending line](https://github.com/iheanyi/iheanyi.github.io/blob/develop/source/layouts/projects_layout.erb#L2).

There seem to be more of these scattered throughout the website. Commiting commented code is not only bad practice, but it also slows down your website's response time by unnecessarily making the footprint of the page larger.

**Comment by iheanyi** [comment]
I hate you so much @GRardB, lol.
